Repository OpenWiseSolutions/openhub-framework, pull requests merged in 2018-03, with the labels that each got.

#77 NOJIRA: RequestSending & ResponseReceive EventNotifiers config
  core/src/main/java/org/openhubframework/openhub/core/reqres/RequestSendingEventNotifier.java
  core/src/main/java/org/openhubframework/openhub/core/reqres/ResponseReceiveEventNotifier.java
  core/src/test/java/org/openhubframework/openhub/core/reqres/RequestResponseTest.java
Labels: bug

#78 Readme change
  README.md
Labels: enhancement

#79 Merge bugfixes from R2.0
  README.md
  admin-console/src/services/api.service.js
  core/src/main/java/org/openhubframework/openhub/core/reqres/RequestSendingEventNotifier.java
  core/src/main/java/org/openhubframework/openhub/core/reqres/ResponseReceiveEventNotifier.java
  core/src/test/java/org/openhubframework/openhub/core/reqres/RequestResponseTest.java
  web/src/main/java/org/openhubframework/openhub/admin/web/services/wsdl/rest/WsdlController.java
  web/src/main/java/org/openhubframework/openhub/config/WebConfigurer.java
  web/src/main/resources/application.properties
Labels: port of bugfixes

#80 OHFJIRA-89 offline mode for GUI
  admin-console/config/webpack.config.js
  admin-console/public/favicon.ico
  admin-console/public/favicon.png
  admin-console/public/humans.txt
  admin-console/public/offline/fonts/index.css
  admin-console/public/offline/fonts/materialicons/v36/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmEU9fABc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmEU9fBxc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmEU9fCBc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmEU9fCRc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmEU9fChc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmEU9fCxc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmSU5fABc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmSU5fBxc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmSU5fCBc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmSU5fCRc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmSU5fChc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmSU5fCxc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmWUlfABc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmWUlfBBc4AMP6lQ.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmWUlfBxc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmWUlfCBc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmWUlfCRc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmWUlfChc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOlCnqEu92Fr1MmWUlfCxc4AMP6lbBP.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOmCnqEu92Fr1Mu5mxKKTU1Kvnz.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOmCnqEu92Fr1Mu72xKKTU1Kvnz.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOmCnqEu92Fr1Mu7GxKKTU1Kvnz.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOmCnqEu92Fr1Mu7WxKKTU1Kvnz.woff2
  admin-console/public/offline/fonts/roboto/v18/KFOmCnqEu92Fr1Mu7mxKKTU1Kvnz (1).woff2
  admin-console/public/offline/fonts/roboto/v18/KFOmCnqEu92Fr1Mu7mxKKTU1Kvnz.woff2
  admin-console/public/offline/styles/flatpickr/3.0.5-1/themes/material_blue.css
  admin-console/public/offline/styles/react-redux-toastr/5.0/react-redux-toastr.min.css
  admin-console/src/index.html
  admin-console/src/main.js
Labels: bug
