Repository OpenWiseSolutions/openhub-framework, pull requests merged in 2020-04, with the labels that each got.

#110 [NOJIRA] : travis - build image switch to openjdk8
  .travis.yml
Labels: improvement

#112 [OHFJIRA-107] : fixed final message processing of messages without re…
  core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
  core/src/test/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessorTest.java
Labels: bug

#113 Bugfix from release/2.1 to develop
  core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
  core/src/test/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessorTest.java
Labels: port of bugfixes

#114 [OHFJIRA-109] : changed selection of partly failed and postponed mess…
  core-spi/src/main/java/org/openhubframework/openhub/spi/msg/MessageService.java
  core/src/main/java/org/openhubframework/openhub/core/common/asynch/msg/MessageServiceImpl.java
  core/src/main/java/org/openhubframework/openhub/core/common/asynch/queue/MessagesPoolImpl.java
  core/src/main/java/org/openhubframework/openhub/core/common/dao/MessageDao.java
  core/src/main/java/org/openhubframework/openhub/core/common/dao/MessageDaoJpaImpl.java
  core/src/test/java/org/openhubframework/openhub/core/common/asynch/db/MessagesPoolDbTest.java
  core/src/test/java/org/openhubframework/openhub/core/common/asynch/msg/MessageServiceTest.java
Labels: improvement
